// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

public partial class TbMedicoPacienteDTO
{
    [Key]
    [Column("IdMedico_Paciente")]
    public TbMedicoPaciente tbMedicoPaciente { get; set; }

    public TbPaciente tbPaciente { get; set; }

    public int IdProfissional { get; set; }    

    public int IdMedicoPaciente {  set; get; }

    public int IdPaciente { get; set; }
}