// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbPaciente")]
public partial class TbPacienteDTO
{
    [Key]
    public int IdPaciente { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("RG")]
    [StringLength(15)]
    [Unicode(false)]
    [Display(Name="RG")]
    public string Rg { get; set; }

    [Required]
    [Column("CPF")]
    [StringLength(15)]
    [Unicode(false)]
    [Display(Name="CPF")]
    public string Cpf { get; set; }

    [Display(Name = "Data de Nascimento")]
    public DateOnly DataNascimento { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    [Display(Name = "Nome do Responsável")]
    public string NomeResponsavel { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Sexo { get; set; }

    public int Etnia { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Bairro { get; set; }

    [Display(Name = "Cidade")]
    public string NomeCidade { get; set; }
    public int? IdCidade { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string TelResidencial { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string TelComercial { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string TelCelular { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    [Display(Name = "Profissão")]
    public string Profissao { get; set; }
    [Display(Name = "Atleta")]
    public string Atleta { get; set; }
    [Display(Name = "Gestante")]
    public string Gestante { get; set; }

    public bool possuiPacientes { get; set; }

    public string MensagemPacientes { get; set; }
    
}
